### ISSUE TITLE
Add metric to track TLS certs that are pending too long

### ISSUE THREAD

**Issue by maleck13** [Kuadrant/kcp-glbc#128]

**Comment by david-martin** [comment]
@maleck13 Is this satisfied by the `glbc_tls_certificate_pending_request_count` metric?
https://github.com/Kuadrant/kcp-glbc/blob/97851d9b5ca65af713871958ab42df041d2f26fe/pkg/tls/metrics.go#L28

**Comment by david-martin** [comment]
closing as done in #72
