### ISSUE TITLE
Integrate with the KCP advanced scheduling feature KCP 0.5

### ISSUE THREAD

**Issue by maleck13** [Kuadrant/kcp-glbc#167]
**What**

Recently the advanced scheduling feature merged in KCP https://github.com/kcp-dev/kcp/pull/942. This is something we need to integrate with in order to provide traffic management when a workload is removed from a cluster. 

- Investigate using this feature to prevent deletion of a workload from a pcluster when an ingress we manage is targeting that workload using a finalizer
- multiple ingress status blocks will be aggregated to an annotation, we need to parse this in order to be able to get the multiple load balancer ip addresses. 
- advanced scheduling needs to be enabled per workload cluster
- Put together a proposal for how we will use this feature within the context of GLBC

Requires https://github.com/Kuadrant/kcp-glbc/issues/197

**Comment by philbrookes** [comment]
prior art for workload migration across workloadclusters: https://github.com/Kuadrant/kcp-glbc/pull/41/files

**Comment by mikenairn** [comment]
Requires https://github.com/Kuadrant/kcp-glbc/issues/197

**Comment by maleck13** [comment]
@philbrookes do we consider this done now? Wondering how we capture there is work to complete it with the 0.6 update

**Comment by philbrookes** [comment]
Shall I make a follow-on to update scheduling to work with features in 0.6.0?

**Comment by maleck13** [comment]
Maybe put under the tasks for the 0.6 issue?
