### ISSUE TITLE
Add e2e test that verifies there is no reconciler activity on an idle system

### ISSUE THREAD

**Issue by chirino** [Kuadrant/kcp-glbc#180]
e2e test should expand on #162 but at some point after the app is deployed but before it is cleaned up, we should monitor the reconcile metrics of the glbc controller to make sure no unexpected reconcile loops are being triggered. 

Unexpected reconcile loops can sneak if a watched resource is continually changed due to the reconcile loop.

**Comment by astefanutti** [comment]
It turned out it required #195, #203 and #204 to make the new check added in #194, that asserts no reconciliation occurs after the system reaches a stationary state, pass.

**Comment by chirino** [comment]
Nice!
