### ISSUE TITLE
multi-workspaces support with single compute service APIExport

### ISSUE THREAD

**Issue by astefanutti** [Kuadrant/kcp-glbc#237]
Here is list of actions that have currently been identified to make the GLBC multi-workspaces capable: 

- [x] Support CREATE and DELETE requests via APIExport virtual API server: kcp-dev/kcp#1283
- [x] Create a ClusterRole with a rule on the APIExport content sub-resources, and a ClusterRoleBinding to the GLBC ServiceAccount: #247 
- [x] #278
- [x] #279

Note that once the above actions are done, it'll only be limited to workspaces that have bound a single compute service APIExport. Alleviating that limitation is tracked in kcp-dev/kcp#1334.

**Comment by maleck13** [comment]
For the second item is that 
the concept of using an empty claim based on?  https://github.com/kcp-dev/kcp/pull/1244

For the 4th item is that something we control or something we need from KCP?

**Comment by maleck13** [comment]
@astefanutti the remaining items do they depend on kcp 0.6.0? Wondering if we could start progressing the claim idea against master to see does it work for us and feeding back to KCP any issues we hit? What I am not sure on is if post 0.6.0 will we be still limited to 1 compute workspace?

So post 0.6.0 would it be the case that you can create a workspace but you would have to bind to our compute workspace and then create a binding for DNSRecord?

**Comment by maleck13** [comment]
@mikenairn do we want to close this or expand it based on what we have learned and the fact we are not there yet?

**Comment by mikenairn** [comment]
> @mikenairn do we want to close this or expand it based on what we have learned and the fact we are not there yet?

I think this can be closed now, what is described is done.

**Comment by maleck13** [comment]
Everything needed to support multiple workspaces as it exists currently in KCP is in place. In the future we will need to do further work to allow us to work with multiple compute workspaces
