### ISSUE TITLE
Soft finalizer annotations are not being removed from secrets

### ISSUE THREAD

**Issue by mikenairn** [Kuadrant/kcp-glbc#309]
Priority: High

The soft finalizers we are adding as part of the workload migration i.e `"finalizers.workload.kcp.dev/kcp-cluster-1": "kuadrant.dev/glbc-migration"` are not being removed on secrets and so KCP never removes it's own finalizer to allow the secrets to be deleted.

## Expected Behaviour
* GLBC should remove *all* finalizers it's adding to all resources including tls cert secrets

## Actual Behaviour
* `kuadrant.dev/glbc-migration` is left on tls secrets in user and glbc workspaces. Manually removing them allows the secret to delete as expected.

## Additional Information

* This test should be added back as part of this fix https://github.com/Kuadrant/kcp-glbc/pull/308/commits/ef8342ccb9ac0366d78207231a308a6810c1d620#diff-f11d178becad090bb0fa903c300e5ab0091d4c4e59c1f6bbecc9a505914af723

**Comment by david-martin** [comment]
@philbrookes @maleck13 
Should the annotation `"finalizers.workload.kcp.dev/kcp-cluster-1": "kuadrant.dev/glbc-migration"` even be put on secrets? Would the migration break without it?
I believe it would only be added indirectly by logic that's currently being removed in #316.
Only Ingress, Deployments and Services directly add this annotation by calling the workloadMigration reconciler:
- https://github.com/Kuadrant/kcp-glbc/blob/main/pkg/reconciler/deployment/deployment.go#L13
- https://github.com/Kuadrant/kcp-glbc/blob/main/pkg/reconciler/ingress/ingress_reconciler.go#L33
- https://github.com/Kuadrant/kcp-glbc/blob/main/pkg/reconciler/service/service.go#L12

So perhaps merging #316 would fix this?

**Comment by maleck13** [comment]
I think we do need that otherwise I would expect the syncer would remove the secret from the current workload cluster and so would break tls?

**Comment by david-martin** [comment]
> I think we do need that otherwise I would expect the syncer would remove the secret from the current workload cluster and so would break tls?

@maleck13 After getting a better understanding of the migration annotation logic, I think we'll need to watch secrets and apply the migration (& deleteAt) annotations in a similar way to above.
The copying of the labels & annotations (now removed in #316 ) would only have helped with the initial migration, but not with cleaning up afterwards. I don't know if they were added intentionally to allow for migration to wait, but either way this isn't a trivial fix.
If you're in agreement, I can look at adding a new reconciler for certificate secrets & manages the annotations.

**Comment by maleck13** [comment]
> The copying of the labels & annotations (now removed in https://github.com/Kuadrant/kcp-glbc/pull/316 ) would only have helped with the initial migration, but not with cleaning up afterwards. I don't know if they were added intentionally to allow for migration to wait, but either way this isn't a trivial fix.

So that initial change removes the unneeded labels from the secrets that are created by the cert-manager in the glbc workspace. Which I think is fine as we don't want the labels on those.
As you say, this leaves a gap with the copied secret, which we do want the labels/annotations on. I guess using the pattern used for deployments is the way to go currently.  https://github.com/Kuadrant/kcp-glbc/blob/main/pkg/reconciler/deployment/deployment.go cc @philbrookes
