### ISSUE TITLE
GLBC goes into infinite loop when deleting ingress with advanced scheduling disabled(glbc)/enabled(kcp)

### ISSUE THREAD

**Issue by mikenairn** [Kuadrant/kcp-glbc#361]
Priority: High (choose one, remove the other options)

GLBC goes into an infinite loop trying to delete an ingress when the KCP advanced scheduling features are enabled on a sync target, and the [advanced scheduling features are disabled in GLBC](https://github.com/Kuadrant/kcp-glbc/pull/334)

## Expected Behaviour
* Ingress should delete as expected

## Actual Behaviour
* GLBC controller goes into an infinite loop trying to delete the ingress

### Steps to Reproduce the Problem

1. Add a sync target with KCP advanced scheduling enabled
2. Start GLBC with GLBC advanced scheduling disabled
3. Create the sample echo service
4. Delete the sample echo service ingress

## Suggested Resolution
*

## Additional Information

*

**Comment by maleck13** [comment]
cc @philbrookes

**Comment by philbrookes** [comment]
https://github.com/kcp-dev/kcp/issues/1891

**Comment by maleck13** [comment]
I think we can remove this from the sprint for now then
