### ISSUE TITLE
Update grafana dashboards to show environment info

### ISSUE THREAD

**Issue by maleck13** [Kuadrant/kcp-glbc#376]
**What**

- currently our grafana drop down is difficult to read. Using a label on the namespace rather than the namespace name should help us know which env we are targeting 
- We have labels on the controller deployment to indicate which env we are in

- [ ] add new panel with env info

**Comment by david-martin** [comment]
The [kube_deployment_labels](https://github.com/kubernetes/kube-state-metrics/blob/master/docs/deployment-metrics.md) metric will need to be added to the federation config https://github.com/Kuadrant/kcp-glbc/blob/main/config/observability/openshift/monitoring_resources/federation-config.yaml#L4
