### ISSUE TITLE
Create a dev guide for working on GLBC using a MAC

### ISSUE THREAD

**Issue by maleck13** [Kuadrant/kcp-glbc#59]
**What**

Using the local kind cluster with DNS in AWS is tricky at the moment and generally means we end using a remote cluster when needing to test something DNS related. 
Investigate whether it is possible to have the DNS resolve to the local kind cluster on a mac
If we figure it out, add docs for others to be able to achieve the same

**Comment by philbrookes** [comment]
PR: https://github.com/Kuadrant/kcp-glbc/pull/88
