### ISSUE TITLE
Move to a deployed syncer model (kcp 0.4)

### ISSUE THREAD

**Issue by maleck13** [Kuadrant/kcp-glbc#79]
KCP is  removing support for push mode sync. This means we will have to have the sync component deployed to our physical clusters with enough permissions to sync our resources. 
We need to update our tests to use this model. Also any deployment and local setup scripts should also use this model 
https://github.com/kcp-dev/kcp/blob/main/docs/syncer.md#instructions

Related KCP PRs:
* https://github.com/kcp-dev/kcp/pull/881
* https://github.com/kcp-dev/kcp/pull/911
* https://github.com/kcp-dev/kcp/pull/909

Update kcp-glbc local setup, e2e tests and docs to use [release-0.4](https://github.com/kcp-dev/kcp/tree/release-0.4) of kcp which includes all the above syncer changes and has already been deployed to the stable kcp hosted environment.

**Done**

- [ ] e2e tests updated to use deployed syncer (kcp 0.4)
- [ ] local set up updated to use deployed syncer (kcp 0.4)
- [ ] docs updated to reflect the new process for adding a workload cluster (kcp 0.4)

**Comment by maleck13** [comment]
https://github.com/kcp-dev/kcp/pull/911/files

**Comment by maleck13** [comment]
@philbrookes @astefanutti I think we need to pick this up next week as they are at 0.4.0 code freeze now

**Comment by astefanutti** [comment]
@maleck13 right, that's going to become a priority.
