### ISSUE TITLE
Refactor and Harden TLS certificate management

### ISSUE THREAD

**Issue by maleck13** [Kuadrant/kcp-glbc#83]
**What**

When adding TLS support, we identified that we should have something reconciling the Issuer(s), also when adding metrics we identified that we should have a controller watching the certificate resource directly rather than just the secret it creates. It is important that as part of this work, we consider how we would reconstitute state if we moved our controller to a new cluster (would we create a new set of certificates etc). We should think of the cluster we are deployed to as fungible 

- [x] #102
- [x] #127
- [x] #173
- [x] Break up reconcilers and make testable
- [x]  Have the metrics central to the ingress package
- [x] remove need for the secret controller
- [x] Report TLS certificate status on the Ingress object
 - [x] #126

**Comment by maleck13** [comment]
@astefanutti I am not sure if we need to have a controller watching the certificates, but rather the when the ingress controller reconciles it check the certificate resource status?

**Comment by astefanutti** [comment]
@maleck13 my current thinking is that the best approach would be to have an informer watching the Certificates in the control cluster, but enqueueing the corresponding Ingresses in KCP. That would be the same as calling `EnqueueRequestForOwner` from controller-runtime, but cross-clusters.

**Comment by astefanutti** [comment]
So there would be only one controller, for Ingress, but its reconcile loop would also be triggered on Certificates events.

**Comment by maleck13** [comment]
Yes ok this makes sense to me. So when something on the certificate changed we could then update the ingress . We could probably also do the same for the secrets

**Comment by astefanutti** [comment]
Right, ideally that should be only the TLS specific code, but that might be tricky to keep track of the source that triggered the reconciliation, with the work-queue in between. I think that'd be acceptable to trigger a full reconcile loop, and favor simplicity over optimisation, assuming the Certificate API does not update too frequently, and the Ingress reconcile loop should be idempotent and only call external service like Route53 when necessary.

**Comment by astefanutti** [comment]
The e2e test has been added with #114.

**Comment by maleck13** [comment]
https://github.com/Kuadrant/kcp-glbc/pull/241

refactor completed. Only 1 piece remains which is to add an informer for user workspace secrets. I will add a follow on for this
