### ISSUE TITLE
Add e2e tests for our exposed certificate metrics

### ISSUE THREAD

**Issue by maleck13** [Kuadrant/kcp-glbc#95]
**What**

We want to be able to verify that our metrics being exposed are exposing the correct values

[ ] The test should create the resources the controller expects in a logical order, we can then verify the metrics exposed match the resources we created

**Comment by maleck13** [comment]
@astefanutti not sure creating resources will be enough? if we create a certificate resource outside of the controller in the right shape, that may not increment certain metrics right? Such as number of certificates created?

**Comment by astefanutti** [comment]
I think it could potentially work, for example if the test logic creates the TLS Secret after a period of time, and update the Certificate resource status, then the informer handlers would queue the events for further reconciliation.

**Comment by maleck13** [comment]
@astefanutti could you put a size label on this
